# Generated by Django 4.0.4 on 2022-05-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortURL', models.CharField(max_length=10, unique=True)),
                ('windowsURL', models.URLField(blank=True, verbose_name='Windows')),
                ('macURL', models.URLField(blank=True, verbose_name='Mac OS')),
                ('androidURL', models.URLField(blank=True, verbose_name='Android')),
                ('iosURL', models.URLField(blank=True, verbose_name='IOS')),
                ('otherURL', models.URLField(blank=True, verbose_name='Others')),
            ],
        ),
    ]
