# Generated by Django 4.0.4 on 2022-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pythonUseragentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('browser_type', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=50)),
                ('os_type', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('device_family', models.CharField(max_length=50)),
            ],
        ),
    ]
