# Generated by Django 4.0.4 on 2022-05-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_pythonuseragentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pythonUseragentModel',
        ),
    ]
