# Generated by Django 4.0.4 on 2022-05-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0004_pythonuseragentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonuseragentmodel',
            name='incoming_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pythonInfo', to='url_short.linksmodel'),
        ),
    ]
