# Generated by Django 4.0.4 on 2022-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0005_alter_pythonuseragentmodel_incoming_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsUseragentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_codeName', models.CharField(max_length=200)),
                ('browser_version', models.CharField(max_length=200)),
                ('browser_language', models.CharField(max_length=200)),
                ('cookies_enabled', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('user_agent_header', models.CharField(max_length=200)),
            ],
        ),
    ]
