# Generated by Django 4.0.4 on 2022-05-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsuseragentmodel',
            name='pyID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jsInfo', to='url_short.pythonuseragentmodel'),
        ),
    ]
