# Generated by Django 4.0.4 on 2022-05-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0009_alter_jsuseragentmodel_pyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonuseragentmodel',
            name='incoming_link',
        ),
        migrations.DeleteModel(
            name='jsUseragentModel',
        ),
        migrations.DeleteModel(
            name='linksModel',
        ),
        migrations.DeleteModel(
            name='pythonUseragentModel',
        ),
    ]
