# Generated by Django 4.0.4 on 2022-05-25 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('url_short', '0010_remove_pythonuseragentmodel_incoming_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='linksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortURL', models.CharField(max_length=10, unique=True)),
                ('windowsURL', models.URLField(blank=True, verbose_name='Windows')),
                ('macURL', models.URLField(blank=True, verbose_name='Mac OS')),
                ('androidURL', models.URLField(blank=True, verbose_name='Android')),
                ('iosURL', models.URLField(blank=True, verbose_name='IOS')),
                ('otherURL', models.URLField(blank=True, verbose_name='Others')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pythonUseragentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('browser_type', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=50)),
                ('os_type', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('device_family', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('incoming_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pythonInfo', to='url_short.linksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='jsUseragentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_codeName', models.CharField(max_length=200)),
                ('browser_version', models.CharField(max_length=200)),
                ('browser_language', models.CharField(max_length=200)),
                ('cookies_enabled', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('user_agent_header', models.CharField(max_length=200)),
                ('timezone_utc', models.CharField(max_length=10)),
                ('timezone_place', models.CharField(max_length=50)),
                ('screen_size', models.CharField(max_length=15)),
                ('battery_level', models.CharField(blank=True, max_length=5)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('incoming_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jsInfo', to='url_short.linksmodel')),
                ('pyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jsInfo', to='url_short.pythonuseragentmodel')),
            ],
        ),
    ]
