# Generated by Django 4.0.4 on 2022-05-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsuseragentmodel',
            name='incoming_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jsInfo', to='url_short.linksmodel'),
        ),
    ]
