# Generated by Django 4.0.4 on 2022-05-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0013_alter_jsuseragentmodel_incoming_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsuseragentmodel',
            name='incoming_link',
        ),
    ]
